export const UPDATE_PRODUCT_PAGE = 'UPDATE_PRODUCT_PAGE'
export const UPDATE_PRODUCT_LIMIT = 'UPDATE_PRODUCT_LIMIT'
export const UPDATE_ORDER_PAGE = 'UPDATE_ORDER_PAGE'
export const UPDATE_ORDER_LIMIT = 'UPDATE_ORDER_LIMIT'